// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package database

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID        string
	Name      string
	Url       string
	UserID    string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type User struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	ApiKey    string
}
